Colormode: 0
FIRA:
  Center: {Camera_high: 0, Center_X: 0, Center_Y: 0, Front: 0, Inner: 0, Outer: 0}
  FPS: 0
  HSV:
    Ball: [0, 360, 0, 255, 0, 255]
    Blue: [0, 360, 0, 255, 0, 255]
    Green: [0, 360, 0, 255, 0, 255]
    Yellow: [0, 360, 0, 255, 0, 255]
    black: {angle: 0, gray: 0}
    white: {angle: 0, gray: 0}
  scan: [21, 75, 142, 101, 101, 114, 205, 220, 199, 53, 26]
  scan_para: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
camera:
  image:
    compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
    compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
    theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
colormode: 0
interface:
  parametercenter: [369, 221, 223, 236, 146, 0]
rosbridge_websocket: {address: '', authenticate: false, delay_between_messages: 0,
  fragment_timeout: 600, max_message_size: None, port: 9090, retry_startup_delay: 5}
rosdistro: 'indigo

  '
roslaunch:
  uris: {host_leokim_virtual_machine__35705: 'http://leokim-virtual-machine:35705/',
    host_leokim_virtual_machine__37142: 'http://leokim-virtual-machine:37142/', host_leokim_virtual_machine__47054: 'http://leokim-virtual-machine:47054/',
    host_leokim_virtual_machine__51567: 'http://leokim-virtual-machine:51567/', host_leokim_virtual_machine__52995: 'http://leokim-virtual-machine:52995/',
    host_leokim_virtual_machine__59030: 'http://leokim-virtual-machine:59030/'}
rosversion: '1.11.20

  '
run_id: 5032d8e6-1aa1-11e7-84ce-000c2955540b
usb_cam:
  image_raw:
    compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
    compressedDepth: {depth_max: 10.0, depth_quantization: 100.0, png_level: 9}
    theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
